/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.HomeController;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.Timer;

/**
 *
 * @author hp
 */
public class HomeForm extends javax.swing.JFrame {

    /**
     * Creates new form Home2
     */
    private HomeController controller;

    public HomeForm() {
        System.out.println("INICIO");
        initComponents();
        controller = new HomeController(this);
        HoraAtual();
        System.out.println("FINALIZOU");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnHeader = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblVersao = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        lblPesquisa = new javax.swing.JLabel();
        jLabel_Data = new javax.swing.JLabel();
        jLabel_Hora = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        pnConteiner = new javax.swing.JLayeredPane();
        pnModo1 = new javax.swing.JPanel();
        pnMais = new javax.swing.JPanel();
        lblMais = new javax.swing.JLabel();
        pnEntrada = new javax.swing.JPanel();
        lblEntrada = new javax.swing.JLabel();
        pnProduto = new javax.swing.JPanel();
        lblProduto = new javax.swing.JLabel();
        pnDashBoard = new javax.swing.JPanel();
        lblDashBoard = new javax.swing.JLabel();
        pnPedido = new javax.swing.JPanel();
        lblPedido = new javax.swing.JLabel();
        pnExpedicao = new javax.swing.JPanel();
        lblExpedicao = new javax.swing.JLabel();
        pnModo2 = new javax.swing.JPanel();
        pnCfop = new javax.swing.JPanel();
        lblCfop = new javax.swing.JLabel();
        pnNcm = new javax.swing.JPanel();
        lblNcm = new javax.swing.JLabel();
        pnHome = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        pnUnidade = new javax.swing.JPanel();
        lblUnidade = new javax.swing.JLabel();
        pnRelatorio = new javax.swing.JPanel();
        lblRelatorio = new javax.swing.JLabel();
        pnMais2 = new javax.swing.JPanel();
        lblMais2 = new javax.swing.JLabel();
        pnModo3 = new javax.swing.JPanel();
        pnConfiguracao = new javax.swing.JPanel();
        lblConfiguracao = new javax.swing.JLabel();
        pnBranco2 = new javax.swing.JPanel();
        lblBranco2 = new javax.swing.JLabel();
        pnBranco1 = new javax.swing.JPanel();
        lblBranco1 = new javax.swing.JLabel();
        pnHome1 = new javax.swing.JPanel();
        lblHome1 = new javax.swing.JLabel();
        pnUsuario = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        pnEmpresa1 = new javax.swing.JPanel();
        lblEmpresa1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnMain.setBackground(new java.awt.Color(204, 204, 204));
        pnMain.setPreferredSize(new java.awt.Dimension(860, 465));

        pnHeader.setBackground(new java.awt.Color(153, 153, 255));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sistema-solar-128.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("SysEstoque ");

        lblVersao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblVersao.setForeground(new java.awt.Color(255, 255, 255));
        lblVersao.setText("Versão 2.0");

        txtPesquisa.setBackground(new java.awt.Color(153, 153, 255));
        txtPesquisa.setForeground(new java.awt.Color(255, 255, 255));

        lblPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lupa.png"))); // NOI18N
        lblPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel_Data.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_Data.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel_Data.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Data.setText("00/00/0000");
        jLabel_Data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_DataMouseClicked(evt);
            }
        });

        jLabel_Hora.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_Hora.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel_Hora.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Hora.setText("00:00:00");

        lblNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNome.setText("Usuario");

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnHeaderLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnHeaderLayout.createSequentialGroup()
                                .addComponent(lblVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(441, Short.MAX_VALUE))
                            .addGroup(pnHeaderLayout.createSequentialGroup()
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeaderLayout.createSequentialGroup()
                                        .addComponent(jLabel_Data)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeaderLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPesquisa)
                        .addGap(36, 36, 36))))
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnHeaderLayout.createSequentialGroup()
                        .addGroup(pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Hora)
                            .addComponent(jLabel_Data))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVersao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesquisa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnHeaderLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblPesquisa, txtPesquisa});

        pnModo1.setBackground(new java.awt.Color(204, 204, 204));
        pnModo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnModo1MouseClicked(evt);
            }
        });

        pnMais.setBackground(new java.awt.Color(255, 255, 255));
        pnMais.setPreferredSize(new java.awt.Dimension(200, 160));
        pnMais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnMaisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnMaisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnMaisMouseExited(evt);
            }
        });

        lblMais.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mais-64.png"))); // NOI18N
        lblMais.setText("Mais opções");
        lblMais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnMaisLayout = new javax.swing.GroupLayout(pnMais);
        pnMais.setLayout(pnMaisLayout);
        pnMaisLayout.setHorizontalGroup(
            pnMaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMais, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnMaisLayout.setVerticalGroup(
            pnMaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMais, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnEntrada.setBackground(new java.awt.Color(255, 255, 255));
        pnEntrada.setPreferredSize(new java.awt.Dimension(200, 160));
        pnEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnEntradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnEntradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnEntradaMouseExited(evt);
            }
        });

        lblEntrada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/caixa-de-entrada-64.png"))); // NOI18N
        lblEntrada.setText("Entradas");
        lblEntrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnEntradaLayout = new javax.swing.GroupLayout(pnEntrada);
        pnEntrada.setLayout(pnEntradaLayout);
        pnEntradaLayout.setHorizontalGroup(
            pnEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnEntradaLayout.setVerticalGroup(
            pnEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnProduto.setBackground(new java.awt.Color(255, 255, 255));
        pnProduto.setPreferredSize(new java.awt.Dimension(200, 160));
        pnProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnProdutoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnProdutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnProdutoMouseExited(evt);
            }
        });

        lblProduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/produtos-64.png"))); // NOI18N
        lblProduto.setText("Produtos");
        lblProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnProdutoLayout = new javax.swing.GroupLayout(pnProduto);
        pnProduto.setLayout(pnProdutoLayout);
        pnProdutoLayout.setHorizontalGroup(
            pnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnProdutoLayout.setVerticalGroup(
            pnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnDashBoard.setBackground(new java.awt.Color(255, 255, 255));
        pnDashBoard.setPreferredSize(new java.awt.Dimension(200, 160));
        pnDashBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnDashBoardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnDashBoardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnDashBoardMouseExited(evt);
            }
        });

        lblDashBoard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDashBoard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDashBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard-64.png"))); // NOI18N
        lblDashBoard.setText("DashBoard");
        lblDashBoard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnDashBoardLayout = new javax.swing.GroupLayout(pnDashBoard);
        pnDashBoard.setLayout(pnDashBoardLayout);
        pnDashBoardLayout.setHorizontalGroup(
            pnDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDashBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnDashBoardLayout.setVerticalGroup(
            pnDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDashBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnPedido.setBackground(new java.awt.Color(255, 255, 255));
        pnPedido.setPreferredSize(new java.awt.Dimension(200, 160));
        pnPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnPedidoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnPedidoMouseExited(evt);
            }
        });

        lblPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pedido-64.png"))); // NOI18N
        lblPedido.setText("Pedidos");
        lblPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnPedidoLayout = new javax.swing.GroupLayout(pnPedido);
        pnPedido.setLayout(pnPedidoLayout);
        pnPedidoLayout.setHorizontalGroup(
            pnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnPedidoLayout.setVerticalGroup(
            pnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnExpedicao.setBackground(new java.awt.Color(255, 255, 255));
        pnExpedicao.setPreferredSize(new java.awt.Dimension(200, 160));
        pnExpedicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnExpedicaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnExpedicaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnExpedicaoMouseExited(evt);
            }
        });

        lblExpedicao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblExpedicao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExpedicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/expedicao-64.png"))); // NOI18N
        lblExpedicao.setText("Expedição");
        lblExpedicao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnExpedicaoLayout = new javax.swing.GroupLayout(pnExpedicao);
        pnExpedicao.setLayout(pnExpedicaoLayout);
        pnExpedicaoLayout.setHorizontalGroup(
            pnExpedicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnExpedicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExpedicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnExpedicaoLayout.setVerticalGroup(
            pnExpedicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnExpedicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExpedicao, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnModo1Layout = new javax.swing.GroupLayout(pnModo1);
        pnModo1.setLayout(pnModo1Layout);
        pnModo1Layout.setHorizontalGroup(
            pnModo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
            .addGroup(pnModo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnModo1Layout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addGroup(pnModo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnDashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                        .addComponent(pnProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnModo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                        .addComponent(pnEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnModo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnExpedicao, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                        .addComponent(pnMais, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                    .addGap(112, 112, 112)))
        );
        pnModo1Layout.setVerticalGroup(
            pnModo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
            .addGroup(pnModo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnModo1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnModo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnDashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(pnPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(pnExpedicao, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnModo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnMais, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(pnEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(pnProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addGap(1, 1, 1)))
        );

        pnModo2.setBackground(new java.awt.Color(204, 204, 204));
        pnModo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnModo2MouseClicked(evt);
            }
        });

        pnCfop.setBackground(new java.awt.Color(255, 255, 255));
        pnCfop.setPreferredSize(new java.awt.Dimension(200, 160));
        pnCfop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnCfopMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnCfopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnCfopMouseExited(evt);
            }
        });

        lblCfop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCfop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCfop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cfop-64.png"))); // NOI18N
        lblCfop.setText("CFOP");
        lblCfop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnCfopLayout = new javax.swing.GroupLayout(pnCfop);
        pnCfop.setLayout(pnCfopLayout);
        pnCfopLayout.setHorizontalGroup(
            pnCfopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCfopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCfop, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnCfopLayout.setVerticalGroup(
            pnCfopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCfopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCfop, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnNcm.setBackground(new java.awt.Color(255, 255, 255));
        pnNcm.setPreferredSize(new java.awt.Dimension(200, 160));
        pnNcm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnNcmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnNcmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnNcmMouseExited(evt);
            }
        });

        lblNcm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNcm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNcm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ncm-64.png"))); // NOI18N
        lblNcm.setText("NCM");
        lblNcm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnNcmLayout = new javax.swing.GroupLayout(pnNcm);
        pnNcm.setLayout(pnNcmLayout);
        pnNcmLayout.setHorizontalGroup(
            pnNcmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNcmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNcm, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnNcmLayout.setVerticalGroup(
            pnNcmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNcmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNcm, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnHome.setBackground(new java.awt.Color(255, 255, 255));
        pnHome.setPreferredSize(new java.awt.Dimension(200, 160));
        pnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnHomeMouseExited(evt);
            }
        });

        lblHome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/botao-home-64.png"))); // NOI18N
        lblHome.setText("Home");
        lblHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnHomeLayout = new javax.swing.GroupLayout(pnHome);
        pnHome.setLayout(pnHomeLayout);
        pnHomeLayout.setHorizontalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnHomeLayout.setVerticalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnUnidade.setBackground(new java.awt.Color(255, 255, 255));
        pnUnidade.setPreferredSize(new java.awt.Dimension(200, 160));
        pnUnidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnUnidadeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnUnidadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnUnidadeMouseExited(evt);
            }
        });

        lblUnidade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUnidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUnidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/metro-64.png"))); // NOI18N
        lblUnidade.setText("Unidades");
        lblUnidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnUnidadeLayout = new javax.swing.GroupLayout(pnUnidade);
        pnUnidade.setLayout(pnUnidadeLayout);
        pnUnidadeLayout.setHorizontalGroup(
            pnUnidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUnidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnUnidadeLayout.setVerticalGroup(
            pnUnidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUnidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnRelatorio.setBackground(new java.awt.Color(255, 255, 255));
        pnRelatorio.setPreferredSize(new java.awt.Dimension(200, 160));
        pnRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnRelatorioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnRelatorioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnRelatorioMouseExited(evt);
            }
        });

        lblRelatorio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/companhia-64.png"))); // NOI18N
        lblRelatorio.setText("Relatório");
        lblRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnRelatorioLayout = new javax.swing.GroupLayout(pnRelatorio);
        pnRelatorio.setLayout(pnRelatorioLayout);
        pnRelatorioLayout.setHorizontalGroup(
            pnRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnRelatorioLayout.setVerticalGroup(
            pnRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnMais2.setBackground(new java.awt.Color(255, 255, 255));
        pnMais2.setPreferredSize(new java.awt.Dimension(200, 160));
        pnMais2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnMais2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnMais2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnMais2MouseExited(evt);
            }
        });

        lblMais2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMais2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMais2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mais-64.png"))); // NOI18N
        lblMais2.setText("Mais opções");
        lblMais2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnMais2Layout = new javax.swing.GroupLayout(pnMais2);
        pnMais2.setLayout(pnMais2Layout);
        pnMais2Layout.setHorizontalGroup(
            pnMais2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMais2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMais2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnMais2Layout.setVerticalGroup(
            pnMais2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMais2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMais2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnModo2Layout = new javax.swing.GroupLayout(pnModo2);
        pnModo2.setLayout(pnModo2Layout);
        pnModo2Layout.setHorizontalGroup(
            pnModo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnModo2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(pnModo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnNcm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnModo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(pnCfop, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnModo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(pnMais2, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addGap(115, 115, 115))
        );
        pnModo2Layout.setVerticalGroup(
            pnModo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnModo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnModo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(pnUnidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(pnRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnModo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnCfop, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(pnNcm, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(pnMais2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnModo3.setBackground(new java.awt.Color(204, 204, 204));
        pnModo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnModo3MouseClicked(evt);
            }
        });

        pnConfiguracao.setBackground(new java.awt.Color(255, 255, 255));
        pnConfiguracao.setPreferredSize(new java.awt.Dimension(200, 160));
        pnConfiguracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnConfiguracaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnConfiguracaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnConfiguracaoMouseExited(evt);
            }
        });

        lblConfiguracao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConfiguracao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfiguracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/configuracao-64.png"))); // NOI18N
        lblConfiguracao.setText("Configurações");
        lblConfiguracao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnConfiguracaoLayout = new javax.swing.GroupLayout(pnConfiguracao);
        pnConfiguracao.setLayout(pnConfiguracaoLayout);
        pnConfiguracaoLayout.setHorizontalGroup(
            pnConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnConfiguracaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfiguracao, javax.swing.GroupLayout.PREFERRED_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnConfiguracaoLayout.setVerticalGroup(
            pnConfiguracaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnConfiguracaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfiguracao, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnBranco2.setBackground(new java.awt.Color(255, 255, 255));
        pnBranco2.setPreferredSize(new java.awt.Dimension(200, 160));
        pnBranco2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnBranco2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnBranco2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnBranco2MouseExited(evt);
            }
        });

        lblBranco2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBranco2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBranco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cfop-64.png"))); // NOI18N
        lblBranco2.setText("Tipo");
        lblBranco2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnBranco2Layout = new javax.swing.GroupLayout(pnBranco2);
        pnBranco2.setLayout(pnBranco2Layout);
        pnBranco2Layout.setHorizontalGroup(
            pnBranco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBranco2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBranco2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnBranco2Layout.setVerticalGroup(
            pnBranco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBranco2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBranco2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnBranco1.setBackground(new java.awt.Color(255, 255, 255));
        pnBranco1.setPreferredSize(new java.awt.Dimension(200, 160));
        pnBranco1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnBranco1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnBranco1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnBranco1MouseExited(evt);
            }
        });

        lblBranco1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBranco1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBranco1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnBranco1Layout = new javax.swing.GroupLayout(pnBranco1);
        pnBranco1.setLayout(pnBranco1Layout);
        pnBranco1Layout.setHorizontalGroup(
            pnBranco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBranco1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBranco1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnBranco1Layout.setVerticalGroup(
            pnBranco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBranco1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBranco1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnHome1.setBackground(new java.awt.Color(255, 255, 255));
        pnHome1.setPreferredSize(new java.awt.Dimension(200, 160));
        pnHome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnHome1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnHome1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnHome1MouseExited(evt);
            }
        });

        lblHome1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/botao-home-64.png"))); // NOI18N
        lblHome1.setText("Home");
        lblHome1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnHome1Layout = new javax.swing.GroupLayout(pnHome1);
        pnHome1.setLayout(pnHome1Layout);
        pnHome1Layout.setHorizontalGroup(
            pnHome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHome1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnHome1Layout.setVerticalGroup(
            pnHome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHome1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnUsuario.setBackground(new java.awt.Color(255, 255, 255));
        pnUsuario.setPreferredSize(new java.awt.Dimension(200, 160));
        pnUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnUsuarioMouseExited(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/perfil-de-usuario-64.png"))); // NOI18N
        lblUsuario.setText("Usuário");
        lblUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnUsuarioLayout = new javax.swing.GroupLayout(pnUsuario);
        pnUsuario.setLayout(pnUsuarioLayout);
        pnUsuarioLayout.setHorizontalGroup(
            pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnUsuarioLayout.setVerticalGroup(
            pnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnEmpresa1.setBackground(new java.awt.Color(255, 255, 255));
        pnEmpresa1.setPreferredSize(new java.awt.Dimension(200, 160));
        pnEmpresa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnEmpresa1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnEmpresa1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnEmpresa1MouseExited(evt);
            }
        });

        lblEmpresa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmpresa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpresa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/companhia-64.png"))); // NOI18N
        lblEmpresa1.setText("Empresas");
        lblEmpresa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnEmpresa1Layout = new javax.swing.GroupLayout(pnEmpresa1);
        pnEmpresa1.setLayout(pnEmpresa1Layout);
        pnEmpresa1Layout.setHorizontalGroup(
            pnEmpresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEmpresa1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmpresa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnEmpresa1Layout.setVerticalGroup(
            pnEmpresa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEmpresa1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmpresa1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnModo3Layout = new javax.swing.GroupLayout(pnModo3);
        pnModo3.setLayout(pnModo3Layout);
        pnModo3Layout.setHorizontalGroup(
            pnModo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
            .addGroup(pnModo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnModo3Layout.createSequentialGroup()
                    .addGap(115, 115, 115)
                    .addGroup(pnModo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnModo3Layout.createSequentialGroup()
                            .addComponent(pnHome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(1, 1, 1))
                        .addComponent(pnBranco1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnModo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                        .addComponent(pnBranco2, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnModo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnEmpresa1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addComponent(pnConfiguracao, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                    .addGap(115, 115, 115)))
        );
        pnModo3Layout.setVerticalGroup(
            pnModo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
            .addGroup(pnModo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnModo3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnModo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnHome1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(pnUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(pnEmpresa1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnModo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnConfiguracao, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                        .addComponent(pnBranco2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                        .addComponent(pnBranco1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                    .addContainerGap()))
        );

        pnConteiner.setLayer(pnModo1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnConteiner.setLayer(pnModo2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnConteiner.setLayer(pnModo3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnConteinerLayout = new javax.swing.GroupLayout(pnConteiner);
        pnConteiner.setLayout(pnConteinerLayout);
        pnConteinerLayout.setHorizontalGroup(
            pnConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnModo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnModo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnModo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnConteinerLayout.setVerticalGroup(
            pnConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnModo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnModo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnConteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnModo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnConteiner)
                .addContainerGap())
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addComponent(pnHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnConteiner)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnModo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnModo1MouseClicked
        pnModo1.setVisible(!true);
        pnModo2.setVisible(true);
        pnModo3.setVisible(!true);
    }//GEN-LAST:event_pnModo1MouseClicked

    private void pnModo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnModo2MouseClicked
        pnModo1.setVisible(!true);
        pnModo2.setVisible(!true);
        pnModo3.setVisible(true);
    }//GEN-LAST:event_pnModo2MouseClicked

    private void pnMaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMaisMouseClicked
        controller.hover(evt, 6);
        controller.showPainel12();
    }//GEN-LAST:event_pnMaisMouseClicked

    private void pnMaisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMaisMouseEntered
        controller.hover(evt, 6);
    }//GEN-LAST:event_pnMaisMouseEntered

    private void pnMaisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMaisMouseExited
        controller.hover(evt, 6);
    }//GEN-LAST:event_pnMaisMouseExited

    private void pnEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnEntradaMouseClicked
        controller.hover(evt, 5);
        controller.showEntrada();
    }//GEN-LAST:event_pnEntradaMouseClicked

    private void pnEntradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnEntradaMouseEntered
        controller.hover(evt, 5);
    }//GEN-LAST:event_pnEntradaMouseEntered

    private void pnEntradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnEntradaMouseExited
        controller.hover(evt, 5);
    }//GEN-LAST:event_pnEntradaMouseExited

    private void pnProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnProdutoMouseClicked
        controller.hover(evt, 4);
        controller.showProduto();
    }//GEN-LAST:event_pnProdutoMouseClicked

    private void pnProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnProdutoMouseEntered
        controller.hover(evt, 4);
    }//GEN-LAST:event_pnProdutoMouseEntered

    private void pnProdutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnProdutoMouseExited
        controller.hover(evt, 4);
    }//GEN-LAST:event_pnProdutoMouseExited

    private void pnDashBoardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDashBoardMouseClicked
        ProdutoForm produtoForm = new ProdutoForm();
        produtoForm.setVisible(true);
    }//GEN-LAST:event_pnDashBoardMouseClicked

    private void pnDashBoardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDashBoardMouseEntered
//        pnDashBoard.setBackground(new java.awt.Color(100, 100, 100));
//        lblDashBoard.setForeground(Color.yellow);
        controller.hover(evt, 1);
    }//GEN-LAST:event_pnDashBoardMouseEntered

    private void pnDashBoardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDashBoardMouseExited
//        pnDashBoard.setBackground(new java.awt.Color(255, 255, 255));
//        lblDashBoard.setForeground(Color.black);
        controller.hover(evt, 1);
    }//GEN-LAST:event_pnDashBoardMouseExited

    private void pnPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPedidoMouseClicked
        controller.hover(evt, 2);
    }//GEN-LAST:event_pnPedidoMouseClicked

    private void pnPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPedidoMouseEntered
        controller.hover(evt, 2);
    }//GEN-LAST:event_pnPedidoMouseEntered

    private void pnPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPedidoMouseExited
        controller.hover(evt, 2);
    }//GEN-LAST:event_pnPedidoMouseExited

    private void pnExpedicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnExpedicaoMouseClicked
        controller.hover(evt, 3);
    }//GEN-LAST:event_pnExpedicaoMouseClicked

    private void pnExpedicaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnExpedicaoMouseEntered
        controller.hover(evt, 3);
    }//GEN-LAST:event_pnExpedicaoMouseEntered

    private void pnExpedicaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnExpedicaoMouseExited
        controller.hover(evt, 3);
    }//GEN-LAST:event_pnExpedicaoMouseExited

    private void pnCfopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnCfopMouseClicked
        controller.hover(evt, 11);
        controller.showNcm();
    }//GEN-LAST:event_pnCfopMouseClicked

    private void pnCfopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnCfopMouseEntered
        controller.hover(evt, 11);
    }//GEN-LAST:event_pnCfopMouseEntered

    private void pnCfopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnCfopMouseExited
        controller.hover(evt, 11);
    }//GEN-LAST:event_pnCfopMouseExited

    private void pnNcmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnNcmMouseClicked
        controller.hover(evt, 10);
        controller.showNcm();
    }//GEN-LAST:event_pnNcmMouseClicked

    private void pnNcmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnNcmMouseEntered
        controller.hover(evt, 10);
    }//GEN-LAST:event_pnNcmMouseEntered

    private void pnNcmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnNcmMouseExited
        controller.hover(evt, 10);
    }//GEN-LAST:event_pnNcmMouseExited

    private void pnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnHomeMouseClicked
        controller.hover(evt, 7);
        controller.showPainel11();
    }//GEN-LAST:event_pnHomeMouseClicked

    private void pnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnHomeMouseEntered
        controller.hover(evt, 7);
    }//GEN-LAST:event_pnHomeMouseEntered

    private void pnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnHomeMouseExited
        controller.hover(evt, 7);
    }//GEN-LAST:event_pnHomeMouseExited

    private void pnUnidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnUnidadeMouseClicked
        controller.hover(evt, 8);
        controller.showUnidade();
    }//GEN-LAST:event_pnUnidadeMouseClicked

    private void pnUnidadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnUnidadeMouseEntered
        controller.hover(evt, 8);
    }//GEN-LAST:event_pnUnidadeMouseEntered

    private void pnUnidadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnUnidadeMouseExited
        controller.hover(evt, 8);
    }//GEN-LAST:event_pnUnidadeMouseExited

    private void pnRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnRelatorioMouseClicked
        controller.hover(evt, 9);
    }//GEN-LAST:event_pnRelatorioMouseClicked

    private void pnRelatorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnRelatorioMouseEntered
        controller.hover(evt, 9);
    }//GEN-LAST:event_pnRelatorioMouseEntered

    private void pnRelatorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnRelatorioMouseExited
        controller.hover(evt, 9);
    }//GEN-LAST:event_pnRelatorioMouseExited

    private void jLabel_DataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_DataMouseClicked
//        DataAtual();
    }//GEN-LAST:event_jLabel_DataMouseClicked

    private void pnConfiguracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnConfiguracaoMouseClicked
        controller.hover(evt, 13);
    }//GEN-LAST:event_pnConfiguracaoMouseClicked

    private void pnConfiguracaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnConfiguracaoMouseEntered
        controller.hover(evt, 13);
    }//GEN-LAST:event_pnConfiguracaoMouseEntered

    private void pnConfiguracaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnConfiguracaoMouseExited
        controller.hover(evt, 13);
    }//GEN-LAST:event_pnConfiguracaoMouseExited

    private void pnBranco2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnBranco2MouseClicked
        controller.hover(evt, 18);
        controller.showTipo();
    }//GEN-LAST:event_pnBranco2MouseClicked

    private void pnBranco2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnBranco2MouseEntered
        controller.hover(evt, 18);
    }//GEN-LAST:event_pnBranco2MouseEntered

    private void pnBranco2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnBranco2MouseExited
        controller.hover(evt, 18);
    }//GEN-LAST:event_pnBranco2MouseExited

    private void pnBranco1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnBranco1MouseClicked
        controller.hover(evt, 17);
    }//GEN-LAST:event_pnBranco1MouseClicked

    private void pnBranco1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnBranco1MouseEntered
        controller.hover(evt, 17);
    }//GEN-LAST:event_pnBranco1MouseEntered

    private void pnBranco1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnBranco1MouseExited
        controller.hover(evt, 17);
    }//GEN-LAST:event_pnBranco1MouseExited

    private void pnHome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnHome1MouseClicked
        controller.hover(evt, 16);
        controller.showPainel11();
    }//GEN-LAST:event_pnHome1MouseClicked

    private void pnHome1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnHome1MouseEntered
        controller.hover(evt, 16);
    }//GEN-LAST:event_pnHome1MouseEntered

    private void pnHome1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnHome1MouseExited
        controller.hover(evt, 16);
    }//GEN-LAST:event_pnHome1MouseExited

    private void pnUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnUsuarioMouseClicked
        controller.hover(evt, 15);
    }//GEN-LAST:event_pnUsuarioMouseClicked

    private void pnUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnUsuarioMouseEntered
        controller.hover(evt, 15);
    }//GEN-LAST:event_pnUsuarioMouseEntered

    private void pnUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnUsuarioMouseExited
        controller.hover(evt, 15);
    }//GEN-LAST:event_pnUsuarioMouseExited

    private void pnEmpresa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnEmpresa1MouseClicked
        controller.hover(evt, 14);
        controller.showEmpresa();
    }//GEN-LAST:event_pnEmpresa1MouseClicked

    private void pnEmpresa1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnEmpresa1MouseEntered
        controller.hover(evt, 14);
    }//GEN-LAST:event_pnEmpresa1MouseEntered

    private void pnEmpresa1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnEmpresa1MouseExited
        controller.hover(evt, 14);
    }//GEN-LAST:event_pnEmpresa1MouseExited

    private void pnModo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnModo3MouseClicked
        pnModo1.setVisible(true);
        pnModo2.setVisible(!true);
        pnModo3.setVisible(!true);
    }//GEN-LAST:event_pnModo3MouseClicked

    private void pnMais2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMais2MouseClicked
        controller.hover(evt, 12);
        controller.showPainel13();
    }//GEN-LAST:event_pnMais2MouseClicked

    private void pnMais2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMais2MouseEntered
        controller.hover(evt, 12);
    }//GEN-LAST:event_pnMais2MouseEntered

    private void pnMais2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMais2MouseExited
        controller.hover(evt, 12);
    }//GEN-LAST:event_pnMais2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeForm().setVisible(true);
            }
        });
    }

    String MenuMinhaData, MenuMinhaDataSistema, MenuMinhaHora;

    public void DataAtual() {
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat formato2 = new SimpleDateFormat("yyyy/MM/dd");
        MenuMinhaData = (formato.format(dataSistema));
        MenuMinhaDataSistema = (formato2.format(dataSistema));
        //MenuMinhaDataSistema = MenuMinhaDataSistema.replace("/", "");
        jLabel_Data.setText(MenuMinhaData);
//        jLabel_Data.setText(MenuMinhaDataSistema);
        System.out.println("Carregou DataAtual");
    }

    public void HoraAtual() {
        Timer timer = new Timer(1000, new hora());
        timer.start();
        DataAtual();
    }

    class hora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            MenuMinhaHora = (String.format("%1$tH:%1$tM:%1$tS", now));
            String MenuMinhaHoraSistema = (String.format("%1$tM:%1$tS", now));
            MenuMinhaHoraSistema = MenuMinhaHora.replace(":", "");
            jLabel_Hora.setText(MenuMinhaHora);
        }

    }

    public void usuarioRecebe(String nome) {
        lblNome.setText(nome);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jLabel_Data;
    public static javax.swing.JLabel jLabel_Hora;
    private javax.swing.JLabel lblBranco1;
    private javax.swing.JLabel lblBranco2;
    private javax.swing.JLabel lblCfop;
    private javax.swing.JLabel lblConfiguracao;
    private javax.swing.JLabel lblDashBoard;
    private javax.swing.JLabel lblEmpresa1;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblExpedicao;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblHome1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMais;
    private javax.swing.JLabel lblMais2;
    private javax.swing.JLabel lblNcm;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPedido;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblRelatorio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUnidade;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVersao;
    private javax.swing.JPanel pnBranco1;
    private javax.swing.JPanel pnBranco2;
    private javax.swing.JPanel pnCfop;
    private javax.swing.JPanel pnConfiguracao;
    private javax.swing.JLayeredPane pnConteiner;
    private javax.swing.JPanel pnDashBoard;
    private javax.swing.JPanel pnEmpresa1;
    private javax.swing.JPanel pnEntrada;
    private javax.swing.JPanel pnExpedicao;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnHome;
    private javax.swing.JPanel pnHome1;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnMais;
    private javax.swing.JPanel pnMais2;
    private javax.swing.JPanel pnModo1;
    private javax.swing.JPanel pnModo2;
    private javax.swing.JPanel pnModo3;
    private javax.swing.JPanel pnNcm;
    private javax.swing.JPanel pnPedido;
    private javax.swing.JPanel pnProduto;
    private javax.swing.JPanel pnRelatorio;
    private javax.swing.JPanel pnUnidade;
    private javax.swing.JPanel pnUsuario;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables

    public HomeController getController() {
        return controller;
    }

    public String getMenuMinhaData() {
        return MenuMinhaData;
    }

    public String getMenuMinhaDataSistema() {
        return MenuMinhaDataSistema;
    }

    public String getMenuMinhaHora() {
        return MenuMinhaHora;
    }

    public static JLabel getjLabel_Data() {
        return jLabel_Data;
    }

    public static JLabel getjLabel_Hora() {
        return jLabel_Hora;
    }

    public JLabel getLblBranco1() {
        return lblBranco1;
    }

    public JLabel getLblBranco2() {
        return lblBranco2;
    }

    public JLabel getLblCfop() {
        return lblCfop;
    }

    public JLabel getLblConfiguracao() {
        return lblConfiguracao;
    }

    public JLabel getLblDashBoard() {
        return lblDashBoard;
    }

    public JLabel getLblEmpresa1() {
        return lblEmpresa1;
    }

    public JLabel getLblEntrada() {
        return lblEntrada;
    }

    public JLabel getLblExpedicao() {
        return lblExpedicao;
    }

    public JLabel getLblHome() {
        return lblHome;
    }

    public JLabel getLblHome1() {
        return lblHome1;
    }

    public JLabel getLblLogo() {
        return lblLogo;
    }

    public JLabel getLblMais() {
        return lblMais;
    }

    public JLabel getLblMais2() {
        return lblMais2;
    }

    public JLabel getLblNcm() {
        return lblNcm;
    }

    public JLabel getLblNome() {
        return lblNome;
    }

    public JLabel getLblPedido() {
        return lblPedido;
    }

    public JLabel getLblPesquisa() {
        return lblPesquisa;
    }

    public JLabel getLblProduto() {
        return lblProduto;
    }

    public JLabel getLblRelatorio() {
        return lblRelatorio;
    }

    public JLabel getLblTitulo() {
        return lblTitulo;
    }

    public JLabel getLblUnidade() {
        return lblUnidade;
    }

    public JLabel getLblUsuario() {
        return lblUsuario;
    }

    public JLabel getLblVersao() {
        return lblVersao;
    }

    public JPanel getPnBranco1() {
        return pnBranco1;
    }

    public JPanel getPnBranco2() {
        return pnBranco2;
    }

    public JPanel getPnCfop() {
        return pnCfop;
    }

    public JPanel getPnConfiguracao() {
        return pnConfiguracao;
    }

    public JLayeredPane getPnConteiner() {
        return pnConteiner;
    }

    public JPanel getPnDashBoard() {
        return pnDashBoard;
    }

    public JPanel getPnEmpresa1() {
        return pnEmpresa1;
    }

    public JPanel getPnEntrada() {
        return pnEntrada;
    }

    public JPanel getPnExpedicao() {
        return pnExpedicao;
    }

    public JPanel getPnHeader() {
        return pnHeader;
    }

    public JPanel getPnHome() {
        return pnHome;
    }

    public JPanel getPnHome1() {
        return pnHome1;
    }

    public JPanel getPnMain() {
        return pnMain;
    }

    public JPanel getPnMais() {
        return pnMais;
    }

    public JPanel getPnMais2() {
        return pnMais2;
    }

    public JPanel getPnModo1() {
        return pnModo1;
    }

    public JPanel getPnModo2() {
        return pnModo2;
    }

    public JPanel getPnModo3() {
        return pnModo3;
    }

    public JPanel getPnNcm() {
        return pnNcm;
    }

    public JPanel getPnPedido() {
        return pnPedido;
    }

    public JPanel getPnProduto() {
        return pnProduto;
    }

    public JPanel getPnRelatorio() {
        return pnRelatorio;
    }

    public JPanel getPnUnidade() {
        return pnUnidade;
    }

    public JPanel getPnUsuario() {
        return pnUsuario;
    }

    public JTextField getTxtPesquisa() {
        return txtPesquisa;
    }

}
